# Organize the data for plottings

In [56]:
import pandas as pd
import json
import os

In [57]:
PS_std_df = pd.read_csv("./data/PS_std.csv",index_col = 0)
PS_species_annot_df = pd.read_excel("./data/Supplementary_table_08092024_v3.xlsx",sheet_name = "data_sheet",skiprows =1,index_col = 0)

In [58]:
PS_std_df.head(2)

,mz,rtime,rtime_left_base,rtime_right_base,parent_masstrack_id,peak_area,cSelectivity,goodness_fitting,snr,detection_counts,...,CD8trans_350K_1,CD8trans_250K_2,CD8TD_750K_1,CD8TD_750K_2,pooled_3,Qstd_3,Blank_3,Klof2_1,Klof2_2,Klof2_3
id_number,,,,,,,,,,,,,,,,,,,,,
F10021,753.5414,301.51,298.99,303.99,5949,1823668931,0.85,0.95,42,17,...,0,294803826,301691563,356991193,0,37446317,0,15775,18839,15819

In [59]:
PS_std_df['annotation_evidence'] = "standard"

In [60]:
PS_std_df['name'] = "15:0-18:1(d7) PS"

In [61]:
PS_species_annot_df.head(2)

,mz,rtime,rtime_left_base,rtime_right_base,cSelectivity,goodness_fitting,snr,annotation_evidence,name,neutral_mass,...,TD-1.2,TD-2.2,Naive-1.3,Naive-2.3,Stem-1.3,Stem-2.3,Trans.-2.3,Trans.-1.3,TD-1.3,TD-2.3
Feature_ID,,,,,,,,,,,,,,,,,,,,,
F16760,846.5271,309.56,307.09,312.16,1.0,0.98,78,in-silico|LMSD,PS 41:7,847.536337,...,-0.118507,0.576845,-0.258313,0.258313,-1.778887,-1.778887,-1.778887,-1.778887,-0.118507,0.576845
F14748,832.5114,307.09,304.82,309.56,1.0,0.70,422,in-silico|LMSD,PS 40:7,833.520687,...,0.140844,0.570131,-0.003671,0.003671,-1.519536,-1.519536,-1.519536,-1.519536,0.140844,0.570131

In [62]:
PS_std_df['name']

id_number
F10021    15:0-18:1(d7) PS
Name: name, dtype: object

In [63]:
set(PS_species_annot_df['annotation_evidence'])

{'in-silico|LMSD', 'in-silico|isotopes|LMSD', 'in-silico|isotopes|LMSD|MS2'}

### Merge the table & allow for plottings
- x as name
- y as rtime
- `cSelectivity` as size
- `color` as annotation_evidence
- `shape` to label those with ms2 and have neutral loss shown

In [77]:
keeps = ["mz", "rtime", "rtime_left_base", "rtime_right_base", "cSelectivity", "goodness_fitting", "snr","annotation_evidence",'name']

mdf = PS_std_df.loc[:,keeps].transpose().merge(PS_species_annot_df.loc[:,keeps].transpose(),left_index = True,right_index = True)

mdf_t= mdf.transpose()

mdf_t = mdf_t.sort_values("mz")

In [78]:
mdf_t.head(2)

,mz,rtime,rtime_left_base,rtime_right_base,cSelectivity,goodness_fitting,snr,annotation_evidence,name
F10021,753.5414,301.51,298.99,303.99,0.85,0.95,42,standard,15:0-18:1(d7) PS
F9821,786.5297,309.99,307.5,312.6,1.0,0.95,22,in-silico|LMSD,PS 36:2

In [81]:
mdf_t.to_csv("./data/cleaned_data.csv")