In [46]:
library(dplyr)
library(ggplot2)

In [47]:
path2table = "./data/cleaned_data.csv"

In [48]:
mdf = read.csv(path2table,row.names = 1, check.names = FALSE)

In [49]:
mdf %>% head(2)

       mz       rtime  rtime_left_base rtime_right_base cSelectivity
F10021 753.5414 301.51 298.99          303.99           0.85
F9821  786.5297 309.99 307.50          312.60           1.00
       goodness_fitting snr annotation_evidence name
F10021 0.95             42  standard            15:0-18:1(d7) PS
F9821  0.95             22  in-silico|LMSD      PS 36:2

In [50]:
mdf

       mz       rtime  rtime_left_base rtime_right_base cSelectivity
F10021 753.5414 301.51 298.99          303.99           0.85
F9821  786.5297 309.99 307.50          312.60           1.00
F11243 798.5262 343.61 341.34          346.10           0.85
F12891 814.5603 304.20 301.72          306.68           0.68
F14748 832.5114 307.09 304.82          309.56           1.00
F15159 834.5291 308.12 305.64          310.64           0.90
F15158 834.5291 301.51 298.99          303.99           0.97
F15555 836.5432 308.74 306.26          311.29           0.91
F16117 840.5755 307.70 305.23          310.21           0.66
F16382 842.5911 347.13 344.65          349.61           0.46
F16760 846.5271 309.56 307.09          312.16           1.00
F16996 848.5423 342.58 340.10          345.06           1.00
F16995 848.5423 333.49 331.42          334.94           0.64
F17899 856.5116 303.79 301.31          306.26           0.76
F17964 858.5278 311.29 310.64          313.03           0.46
F13775 864.5757 309.15 306.68          309.99           0.59
F13774 864.5757 301.72 299.20          304.20           0.74
F13909 866.5913 261.51 259.02          261.92           0.19
F13911 866.5913 329.35 326.87          331.83           0.54
F14095 868.6070 367.01 364.52          369.49           0.69
F14786 876.5717 369.49 367.01          371.98           0.80
F15985 890.5910 316.70 314.12          319.22           0.72
F15984 890.5910 306.47 305.23          308.94           0.96
F16673 896.6378 402.81 400.19          405.42           0.54
       goodness_fitting snr  annotation_evidence         name
F10021 0.95               42 standard                    15:0-18:1(d7) PS
F9821  0.95               22 in-silico|LMSD              PS 36:2
F11243 0.83               11 in-silico|LMSD              PS 37:3
F12891 0.91               32 in-silico|LMSD              PS 38:2
F14748 0.70              422 in-silico|LMSD              PS 40:7
F15159 0.84               58 in-silico|isotopes|LMSD|MS2 PS 40:6
F15158 0.94              133 in-silico|isotopes|LMSD|MS2 PS 40:6
F15555 0.93               31 in-silico|isotopes|LMSD|MS2 PS 40:5
F16117 0.98                6 in-silico|isotopes|LMSD     PS 40:3
F16382 0.98               13 in-silico|isotopes|LMSD     PS 40:2
F16760 0.98               78 in-silico|LMSD              PS 41:7
F16996 0.98             3535 in-silico|isotopes|LMSD     PS 41:6
F16995 0.83               16 in-silico|LMSD              PS 41:6
F17899 0.95               58 in-silico|isotopes|LMSD     PS 42:9
F17964 0.54                2 in-silico|LMSD              PS 42:8
F13775 0.76               35 in-silico|isotopes|LMSD     PS 42:5
F13774 0.97               33 in-silico|isotopes|LMSD     PS 42:5
F13909 0.71                4 in-silico|LMSD              PS 42:4
F13911 0.96               16 in-silico|isotopes|LMSD     PS 42:4
F14095 0.99               21 in-silico|isotopes|LMSD     PS 42:3
F14786 0.86              299 in-silico|LMSD              PS 43:6
F15985 0.97               83 in-silico|isotopes|LMSD     PS 44:6
F15984 0.68               61 in-silico|LMSD              PS 44:6
F16673 0.99               18 in-silico|isotopes|LMSD     PS 44:3

In [51]:
mdf = mdf %>% filter(grepl("MS2|standard", annotation_evidence))

In [52]:
# Sorting by 'rtime'
mdf <- mdf %>% arrange(rtime)

In [53]:
# Plotting with ggplot2
p <- ggplot(mdf, aes(x = rtime, y = name)) +

  # add error bar
  geom_errorbarh(aes(xmin = rtime_left_base, xmax = rtime_right_base), color = "gray", alpha = 0.5) +
  
  geom_point(aes(size = goodness_fitting, color = annotation_evidence)) +
  
  geom_point(data = mdf %>% filter(grepl("MS2", annotation_evidence)),
             aes(size = cSelectivity), color = "red", fill = NA) +
  scale_color_viridis_d(option = "D") +  
  labs(title = "Retention Time with goodness_fitting as Size and Annotation Evidence as Color",
       x = "Retention Time (rtime)", y = "Name", color = "Annotation Evidence") +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 0, hjust = 1)) +
  xlim(250, 350)  # Set retention time range from 0 to 600

In [59]:
ggsave("./data/final_result.pdf",p,width= 9,height = 5)